# Generated by Django 5.0 on 2023-12-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64)),
                ('producent', models.CharField(max_length=32)),
                ('typ', models.CharField(max_length=32)),
                ('plec', models.CharField(max_length=8)),
                ('cena', models.FloatField()),
            ],
        ),
    ]
