# Generated by Django 5.0 on 2023-12-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_typ_produkt_kategoria_produkt_kolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='opis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='produkt',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
