# Generated by Django 5.0 on 2023-12-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produkt_opis_produkt_zdjecie_alter_produkt_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.FloatField(),
        ),
    ]
