# Generated by Django 5.0 on 2023-12-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_client_order_shoes_shoescategory_delete_produkt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RenameModel(
            old_name='ShoesCategory',
            new_name='ShoeCategory',
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('producer', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=8)),
                ('color', models.CharField(default='czarny', max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='zdjecia')),
                ('shoe_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='app.shoecategory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shoe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.shoe'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
    ]
